CREATE TABLE IF NOT EXISTS qr_scans (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    scanned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_agent VARCHAR(1024) NULL,
    referer VARCHAR(1024) NULL,
    ip_address VARCHAR(64) NULL,
    scan_number BIGINT UNSIGNED NOT NULL DEFAULT 0,
    channel ENUM('customer','admin') NOT NULL DEFAULT 'customer',
    qr_id BIGINT UNSIGNED NULL,
    qr_slug VARCHAR(190) NULL,
    destination_key VARCHAR(190) NULL,
    destination_label VARCHAR(255) NULL,
    resolved_url VARCHAR(1024) NULL,
    city VARCHAR(120) NULL,
    region VARCHAR(120) NULL,
    country VARCHAR(120) NULL,
    device VARCHAR(120) NULL,
    browser VARCHAR(120) NULL,
    os VARCHAR(120) NULL,
    language VARCHAR(40) NULL,
    screen VARCHAR(40) NULL,
    INDEX idx_qr_scans_channel (channel),
    INDEX idx_qr_scans_channel_scanned_at (channel, scanned_at),
    INDEX idx_qr_scans_qr_id (qr_id),
    INDEX idx_qr_scans_qr_slug (qr_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
