CREATE TABLE IF NOT EXISTS whatsapp_template_drafts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    draft_name VARCHAR(191) NOT NULL,
    template_name VARCHAR(191) NOT NULL,
    category VARCHAR(64) NOT NULL DEFAULT 'UTILITY',
    language_code VARCHAR(20) NOT NULL DEFAULT 'en',
    header_type VARCHAR(32) NULL,
    header_text TEXT NULL,
    body_text LONGTEXT NULL,
    footer_text TEXT NULL,
    buttons_json LONGTEXT NULL,
    sample_variables_json LONGTEXT NULL,
    example_media_handle VARCHAR(191) NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'draft',
    meta_template_id VARCHAR(191) NULL,
    submitted_at DATETIME NULL,
    last_synced_at DATETIME NULL,
    rejection_reason TEXT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wa_drafts_template (template_name),
    INDEX idx_wa_drafts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_scheduled_messages (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_key VARCHAR(191) NOT NULL,
    transaction_id VARCHAR(191) NOT NULL,
    lead_id BIGINT NULL,
    phone VARCHAR(40) NOT NULL,
    customer_name VARCHAR(191) NULL,
    event_id VARCHAR(191) NULL,
    event_title VARCHAR(191) NULL,
    due_at DATETIME NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_result_code VARCHAR(64) NULL,
    last_result_message VARCHAR(255) NULL,
    payload_json LONGTEXT NULL,
    sent_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_whatsapp_schedule_event_txn (event_key, transaction_id),
    INDEX idx_whatsapp_schedule_due (status, due_at),
    INDEX idx_whatsapp_schedule_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
