CREATE TABLE IF NOT EXISTS whatsapp_event_message_versions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_key VARCHAR(191) NOT NULL,
    source_draft_id BIGINT UNSIGNED NULL,
    version_label VARCHAR(191) NOT NULL,
    template_name VARCHAR(191) NULL,
    language_code VARCHAR(20) NULL,
    category VARCHAR(64) NULL,
    header_type VARCHAR(32) NULL,
    header_text TEXT NULL,
    body_text LONGTEXT NULL,
    footer_text TEXT NULL,
    buttons_json LONGTEXT NULL,
    sample_variables_json LONGTEXT NULL,
    source_template_uid VARCHAR(191) NULL,
    meta_template_uid VARCHAR(191) NULL,
    meta_status VARCHAR(64) NULL,
    is_current TINYINT(1) NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wa_versions_event_key (event_key),
    INDEX idx_wa_versions_current (event_key, is_current)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
